---
packages:
  - ssh
  - vino
  - gnome-tweaks
  - flatpak
  - autokey-gtk
  - cargo
  - ibus-mozc
  - mozc-utils-gui
  - rbenv
  - virtualbox-qt
  - jq
  - fish
  - vagrant
  - rclone-browser
  - ffmpeg
  - v4l2loopback-dkms
  - imagemagick
  - encfs
  - sysstat
  - picard
  - abcde
  - eyed3 # required by abcde
  - lame # required by abcde
  - mpv
  - fzf
  - byobu
  - qemu-kvm
  - nmap
  - virt-manager
  - graphviz
snap_packages:
  - name: tree
  - name: htop
  - name: lxd
#  - name: microk8s # not used yet
#    classic: yes
  - name: multipass
    classic: yes
    channel: beta
  - name: emacs
    classic: yes
  - name: hub
    classic: yes
  - name: teams-for-linux
  - name: node
    channel: 13/stable
    classic: yes
  - name: google-cloud-sdk
    classic: yes
  - name: gimp
  - name: zoom-client
  - name: obs-studio
  - name: youtube-dl
  - name: vlc
  - name: discord
  - name: audacity
  - name: inkscape
  - name: autossh
homebrew_packages:
  - kubectl
  - kind
  - helm
  - terraform
  - gh
  - ccat
  - kompose
  - go
  - poetry
  - awscli
  - cfssl
  - skaffold
  - buildpacks/tap/pack
  - krew
  - tldr
flatpak_packages: []
npm_global_packages:
  - yarn
